name: CI-CD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Autenticação do Usuário no Hub.Dockers
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Construção e Deploy da Imagem no Hub.Dockers
        uses: docker/build-push-action@v3.1.0
        with: 
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
              angelojr0/kube-news:latest
              angelojr0/kube-news:${{github.run_number}}
              
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      - name: Definição do contexto do Kubernetes Kube Config
        uses: Azure/k8s-set-context@v3.0
        with:
            method: kubeconfig
            kubeconfig: ${{secrets.K8S_CONFIG}}
      - name: Efetuação do Deploy no ambiente Kubernetes
        uses: Azure/k8s-deploy@v4.2
        with:
          images: angelojr0/kube-news:${{github.run_number}}
          manifests: k8s/deployment.yaml
            
            
